[dns]
    upstreams = [
        "1.1.1.1"
    ]
    hosts = [

    ]
    ## list hosts in "ip domain" form
    listeningMode = "ALL"

[webserver]
    port = "0.0.0.0:80"
    [webserver.api]
        pwhash = ""
        localAPIAuth = false

[misc]
    etc_dnsmasq = true